// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @returns {$CancellablePromise<string>}
 */
export function ChooseFile() {
    return $Call.ByID(956589294);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function ChooseFolder() {
    return $Call.ByID(2147375612);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function ChooseIcon() {
    return $Call.ByID(883229929);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function ChooseSetupIcon() {
    return $Call.ByID(2369415792);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function OpenPath(path) {
    return $Call.ByID(1774629290, path);
}
