version: '3'

vars:
  APP_NAME: "wails_manager"
  BIN_DIR: "bin"
  CGO_ENABLED: "1"
  PRODUCTION: "true"
  PACKAGE_MANAGER: '{{.PACKAGE_MANAGER | default "npm"}}'
  VITE_PORT: '{{.WAILS_VITE_PORT | default 9245}}'

includes:
  common: ./build/Taskfile.yml
  windows: ./build/windows/Taskfile.yml
  darwin: ./build/darwin/Taskfile.yml
  linux: ./build/linux/Taskfile.yml
  ios: ./build/ios/Taskfile.yml
  android: ./build/android/Taskfile.yml

tasks:
  build:
    summary: Builds the application
    cmds:
      - task: "{{OS}}:build"
        vars:
          APP_NAME: "{{.APP_NAME}}"
          CGO_ENABLED: "{{.CGO_ENABLED}}"
          PRODUCTION: "{{.PRODUCTION}}"

  release:
    summary: Builds the release application
    cmds:
      - task: "{{OS}}:build"
        vars:
          APP_NAME: "{{.APP_NAME}}"
          CGO_ENABLED: "{{.CGO_ENABLED}}"
          PRODUCTION: "{{.PRODUCTION}}"

  package:
    summary: Packages a production build of the application
    cmds:
      - task: "{{OS}}:package"
        vars:
          CGO_ENABLED: "{{.CGO_ENABLED}}"
          PRODUCTION: "true"
          PACKAGE_NAME: "{{.PACKAGE_NAME}}"

  run:
    summary: Runs the application
    cmds:
      - task: "{{OS}}:run"

  dev:
    summary: Runs the application in development mode
    cmds:
      - wails3 dev -config ./build/config.yml -port {{.VITE_PORT}}
