// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Artifact {
    /**
     * Creates a new Artifact instance.
     * @param {Partial<Artifact>} [$$source = {}] - The source object to create the Artifact.
     */
    constructor($$source = {}) {
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {UnixTime}
             */
            this["createdAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Artifact instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Artifact}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Artifact(/** @type {Partial<Artifact>} */($$parsedSource));
    }
}

export class ArtifactConfig {
    /**
     * Creates a new ArtifactConfig instance.
     * @param {Partial<ArtifactConfig>} [$$source = {}] - The source object to create the ArtifactConfig.
     */
    constructor($$source = {}) {
        if (!("outputRoot" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["outputRoot"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ArtifactConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ArtifactConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ArtifactConfig(/** @type {Partial<ArtifactConfig>} */($$parsedSource));
    }
}

export class BuildSettings {
    /**
     * Creates a new BuildSettings instance.
     * @param {Partial<BuildSettings>} [$$source = {}] - The source object to create the BuildSettings.
     */
    constructor($$source = {}) {
        if (!("taskfile" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["taskfile"] = "";
        }
        if (!("task" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["task"] = "";
        }
        if (!("command" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["command"] = [];
        }
        if (!("production" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["production"] = false;
        }
        if (!("cgoEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["cgoEnabled"] = false;
        }
        if (!("appName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["appName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BuildSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BuildSettings}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("command" in $$parsedSource) {
            $$parsedSource["command"] = $$createField2_0($$parsedSource["command"]);
        }
        return new BuildSettings(/** @type {Partial<BuildSettings>} */($$parsedSource));
    }
}

export class EnvironmentReport {
    /**
     * Creates a new EnvironmentReport instance.
     * @param {Partial<EnvironmentReport>} [$$source = {}] - The source object to create the EnvironmentReport.
     */
    constructor($$source = {}) {
        if (!("os" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["os"] = "";
        }
        if (!("arch" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["arch"] = "";
        }
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("checks" in $$source)) {
            /**
             * @member
             * @type {ToolCheck[]}
             */
            this["checks"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnvironmentReport instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EnvironmentReport}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("checks" in $$parsedSource) {
            $$parsedSource["checks"] = $$createField3_0($$parsedSource["checks"]);
        }
        return new EnvironmentReport(/** @type {Partial<EnvironmentReport>} */($$parsedSource));
    }
}

export class LogSnapshot {
    /**
     * Creates a new LogSnapshot instance.
     * @param {Partial<LogSnapshot>} [$$source = {}] - The source object to create the LogSnapshot.
     */
    constructor($$source = {}) {
        if (!("cursor" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cursor"] = 0;
        }
        if (!("lines" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["lines"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogSnapshot instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LogSnapshot}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("lines" in $$parsedSource) {
            $$parsedSource["lines"] = $$createField1_0($$parsedSource["lines"]);
        }
        return new LogSnapshot(/** @type {Partial<LogSnapshot>} */($$parsedSource));
    }
}

export class MacOSConfig {
    /**
     * Creates a new MacOSConfig instance.
     * @param {Partial<MacOSConfig>} [$$source = {}] - The source object to create the MacOSConfig.
     */
    constructor($$source = {}) {
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("appBundle" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["appBundle"] = "";
        }
        if (!("dmgScript" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dmgScript"] = "";
        }
        if (!("background" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["background"] = "";
        }
        if (!("outputName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["outputName"] = "";
        }
        if (!("createDmgPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["createDmgPath"] = "";
        }
        if (!("windowWidth" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["windowWidth"] = 0;
        }
        if (!("windowHeight" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["windowHeight"] = 0;
        }
        if (!("iconSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["iconSize"] = 0;
        }
        if (!("appX" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["appX"] = 0;
        }
        if (!("appY" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["appY"] = 0;
        }
        if (!("applicationsX" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["applicationsX"] = 0;
        }
        if (!("applicationsY" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["applicationsY"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MacOSConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MacOSConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MacOSConfig(/** @type {Partial<MacOSConfig>} */($$parsedSource));
    }
}

export class ManagerSettings {
    /**
     * Creates a new ManagerSettings instance.
     * @param {Partial<ManagerSettings>} [$$source = {}] - The source object to create the ManagerSettings.
     */
    constructor($$source = {}) {
        if (!("theme" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["theme"] = "";
        }
        if (!("language" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["language"] = "";
        }
        if (!("recordLogs" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["recordLogs"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ManagerSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ManagerSettings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ManagerSettings(/** @type {Partial<ManagerSettings>} */($$parsedSource));
    }
}

export class PackageRequest {
    /**
     * Creates a new PackageRequest instance.
     * @param {Partial<PackageRequest>} [$$source = {}] - The source object to create the PackageRequest.
     */
    constructor($$source = {}) {
        if (!("projectDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["projectDir"] = "";
        }
        if (!("platform" in $$source)) {
            /**
             * @member
             * @type {Platform}
             */
            this["platform"] = Platform.$zero;
        }
        if (!("dryRun" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["dryRun"] = false;
        }
        if (!("runBuild" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["runBuild"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PackageRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PackageRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PackageRequest(/** @type {Partial<PackageRequest>} */($$parsedSource));
    }
}

export class PackageResult {
    /**
     * Creates a new PackageResult instance.
     * @param {Partial<PackageResult>} [$$source = {}] - The source object to create the PackageResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["runId"] = undefined;
        }
        if (!("artifacts" in $$source)) {
            /**
             * @member
             * @type {Artifact[]}
             */
            this["artifacts"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["warnings"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PackageResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PackageResult}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType4;
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("artifacts" in $$parsedSource) {
            $$parsedSource["artifacts"] = $$createField3_0($$parsedSource["artifacts"]);
        }
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField4_0($$parsedSource["warnings"]);
        }
        return new PackageResult(/** @type {Partial<PackageResult>} */($$parsedSource));
    }
}

export class PackagingAsset {
    /**
     * Creates a new PackagingAsset instance.
     * @param {Partial<PackagingAsset>} [$$source = {}] - The source object to create the PackagingAsset.
     */
    constructor($$source = {}) {
        if (!("src" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["src"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("required" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["required"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PackagingAsset instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PackagingAsset}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PackagingAsset(/** @type {Partial<PackagingAsset>} */($$parsedSource));
    }
}

export class PackagingConfig {
    /**
     * Creates a new PackagingConfig instance.
     * @param {Partial<PackagingConfig>} [$$source = {}] - The source object to create the PackagingConfig.
     */
    constructor($$source = {}) {
        if (!("schemaVersion" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["schemaVersion"] = 0;
        }
        if (!("project" in $$source)) {
            /**
             * @member
             * @type {ProjectInfo}
             */
            this["project"] = (new ProjectInfo());
        }
        if (!("build" in $$source)) {
            /**
             * @member
             * @type {BuildSettings}
             */
            this["build"] = (new BuildSettings());
        }
        if (!("entry" in $$source)) {
            /**
             * @member
             * @type {ProgramEntry}
             */
            this["entry"] = (new ProgramEntry());
        }
        if (!("assets" in $$source)) {
            /**
             * @member
             * @type {PackagingAsset[]}
             */
            this["assets"] = [];
        }
        if (!("windows" in $$source)) {
            /**
             * @member
             * @type {WindowsConfig}
             */
            this["windows"] = (new WindowsConfig());
        }
        if (!("macos" in $$source)) {
            /**
             * @member
             * @type {MacOSConfig}
             */
            this["macos"] = (new MacOSConfig());
        }
        if (!("artifacts" in $$source)) {
            /**
             * @member
             * @type {ArtifactConfig}
             */
            this["artifacts"] = (new ArtifactConfig());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PackagingConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PackagingConfig}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType5;
        const $$createField2_0 = $$createType6;
        const $$createField3_0 = $$createType7;
        const $$createField4_0 = $$createType9;
        const $$createField5_0 = $$createType10;
        const $$createField6_0 = $$createType11;
        const $$createField7_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("project" in $$parsedSource) {
            $$parsedSource["project"] = $$createField1_0($$parsedSource["project"]);
        }
        if ("build" in $$parsedSource) {
            $$parsedSource["build"] = $$createField2_0($$parsedSource["build"]);
        }
        if ("entry" in $$parsedSource) {
            $$parsedSource["entry"] = $$createField3_0($$parsedSource["entry"]);
        }
        if ("assets" in $$parsedSource) {
            $$parsedSource["assets"] = $$createField4_0($$parsedSource["assets"]);
        }
        if ("windows" in $$parsedSource) {
            $$parsedSource["windows"] = $$createField5_0($$parsedSource["windows"]);
        }
        if ("macos" in $$parsedSource) {
            $$parsedSource["macos"] = $$createField6_0($$parsedSource["macos"]);
        }
        if ("artifacts" in $$parsedSource) {
            $$parsedSource["artifacts"] = $$createField7_0($$parsedSource["artifacts"]);
        }
        return new PackagingConfig(/** @type {Partial<PackagingConfig>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const Platform = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    PlatformAuto: "auto",
    PlatformWindows: "windows",
    PlatformMacOS: "darwin",
    PlatformAll: "all",
};

export class ProgramEntry {
    /**
     * Creates a new ProgramEntry instance.
     * @param {Partial<ProgramEntry>} [$$source = {}] - The source object to create the ProgramEntry.
     */
    constructor($$source = {}) {
        if (!("executablePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["executablePath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProgramEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProgramEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProgramEntry(/** @type {Partial<ProgramEntry>} */($$parsedSource));
    }
}

export class ProjectInfo {
    /**
     * Creates a new ProjectInfo instance.
     * @param {Partial<ProjectInfo>} [$$source = {}] - The source object to create the ProjectInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("bundleId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["bundleId"] = "";
        }
        if (!("author" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["author"] = "";
        }
        if (!("publisher" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["publisher"] = "";
        }
        if (!("homepage" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["homepage"] = "";
        }
        if (!("copyright" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["copyright"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("buildOutputDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["buildOutputDir"] = "";
        }
        if (!("icon" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProjectInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProjectInfo(/** @type {Partial<ProjectInfo>} */($$parsedSource));
    }
}

export class ProjectRecord {
    /**
     * Creates a new ProjectRecord instance.
     * @param {Partial<ProjectRecord>} [$$source = {}] - The source object to create the ProjectRecord.
     */
    constructor($$source = {}) {
        if (!("projectDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["projectDir"] = "";
        }
        if (!("project" in $$source)) {
            /**
             * @member
             * @type {WailsProjectManager}
             */
            this["project"] = (new WailsProjectManager());
        }
        if (!("importedAt" in $$source)) {
            /**
             * @member
             * @type {UnixTime}
             */
            this["importedAt"] = null;
        }
        if (!("lastOpenedAt" in $$source)) {
            /**
             * @member
             * @type {UnixTime}
             */
            this["lastOpenedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectRecord instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProjectRecord}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("project" in $$parsedSource) {
            $$parsedSource["project"] = $$createField1_0($$parsedSource["project"]);
        }
        return new ProjectRecord(/** @type {Partial<ProjectRecord>} */($$parsedSource));
    }
}

export class ScanResult {
    /**
     * Creates a new ScanResult instance.
     * @param {Partial<ScanResult>} [$$source = {}] - The source object to create the ScanResult.
     */
    constructor($$source = {}) {
        if (!("projectDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["projectDir"] = "";
        }
        if (!("score" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["score"] = 0;
        }
        if (!("isWailsProject" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isWailsProject"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScanResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScanResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScanResult(/** @type {Partial<ScanResult>} */($$parsedSource));
    }
}

export class ToolCheck {
    /**
     * Creates a new ToolCheck instance.
     * @param {Partial<ToolCheck>} [$$source = {}] - The source object to create the ToolCheck.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("command" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["command"] = "";
        }
        if (!("found" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["found"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["version"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["path"] = undefined;
        }
        if (!("required" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["required"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Platform | undefined}
             */
            this["platform"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolCheck instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ToolCheck}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToolCheck(/** @type {Partial<ToolCheck>} */($$parsedSource));
    }
}

/**
 * UnixTime stores timestamps as Unix seconds in JSON.
 * @typedef {any} UnixTime
 */

export class WailsAppInfo {
    /**
     * Creates a new WailsAppInfo instance.
     * @param {Partial<WailsAppInfo>} [$$source = {}] - The source object to create the WailsAppInfo.
     */
    constructor($$source = {}) {
        if (!("companyName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["companyName"] = "";
        }
        if (!("productName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["productName"] = "";
        }
        if (!("productIdentifier" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["productIdentifier"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("copyright" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["copyright"] = "";
        }
        if (!("comments" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["comments"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WailsAppInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WailsAppInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WailsAppInfo(/** @type {Partial<WailsAppInfo>} */($$parsedSource));
    }
}

export class WailsFileAssociation {
    /**
     * Creates a new WailsFileAssociation instance.
     * @param {Partial<WailsFileAssociation>} [$$source = {}] - The source object to create the WailsFileAssociation.
     */
    constructor($$source = {}) {
        if (!("ext" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ext"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("iconName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["iconName"] = "";
        }
        if (!("role" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["role"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["mimeType"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WailsFileAssociation instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WailsFileAssociation}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WailsFileAssociation(/** @type {Partial<WailsFileAssociation>} */($$parsedSource));
    }
}

export class WailsProjectConfig {
    /**
     * Creates a new WailsProjectConfig instance.
     * @param {Partial<WailsProjectConfig>} [$$source = {}] - The source object to create the WailsProjectConfig.
     */
    constructor($$source = {}) {
        if (!("info" in $$source)) {
            /**
             * @member
             * @type {WailsAppInfo}
             */
            this["info"] = (new WailsAppInfo());
        }
        if (!("icon" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {WailsFileAssociation[] | undefined}
             */
            this["fileAssociations"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WailsProjectConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WailsProjectConfig}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType14;
        const $$createField2_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("info" in $$parsedSource) {
            $$parsedSource["info"] = $$createField0_0($$parsedSource["info"]);
        }
        if ("fileAssociations" in $$parsedSource) {
            $$parsedSource["fileAssociations"] = $$createField2_0($$parsedSource["fileAssociations"]);
        }
        return new WailsProjectConfig(/** @type {Partial<WailsProjectConfig>} */($$parsedSource));
    }
}

export class WailsProjectManager {
    /**
     * Creates a new WailsProjectManager instance.
     * @param {Partial<WailsProjectManager>} [$$source = {}] - The source object to create the WailsProjectManager.
     */
    constructor($$source = {}) {
        if (!("projectDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["projectDir"] = "";
        }
        if (!("currentPlatform" in $$source)) {
            /**
             * @member
             * @type {Platform}
             */
            this["currentPlatform"] = Platform.$zero;
        }
        if (!("wailsConfig" in $$source)) {
            /**
             * @member
             * @type {WailsProjectConfig}
             */
            this["wailsConfig"] = (new WailsProjectConfig());
        }
        if (!("taskVars" in $$source)) {
            /**
             * @member
             * @type {WailsTaskVars}
             */
            this["taskVars"] = (new WailsTaskVars());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WailsProjectManager instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WailsProjectManager}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType17;
        const $$createField3_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("wailsConfig" in $$parsedSource) {
            $$parsedSource["wailsConfig"] = $$createField2_0($$parsedSource["wailsConfig"]);
        }
        if ("taskVars" in $$parsedSource) {
            $$parsedSource["taskVars"] = $$createField3_0($$parsedSource["taskVars"]);
        }
        return new WailsProjectManager(/** @type {Partial<WailsProjectManager>} */($$parsedSource));
    }
}

export class WailsTaskVars {
    /**
     * Creates a new WailsTaskVars instance.
     * @param {Partial<WailsTaskVars>} [$$source = {}] - The source object to create the WailsTaskVars.
     */
    constructor($$source = {}) {
        if (!("appName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["appName"] = "";
        }
        if (!("production" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["production"] = false;
        }
        if (!("cgoEnabled" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cgoEnabled"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WailsTaskVars instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WailsTaskVars}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WailsTaskVars(/** @type {Partial<WailsTaskVars>} */($$parsedSource));
    }
}

export class WindowsConfig {
    /**
     * Creates a new WindowsConfig instance.
     * @param {Partial<WindowsConfig>} [$$source = {}] - The source object to create the WindowsConfig.
     */
    constructor($$source = {}) {
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("innoScript" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["innoScript"] = "";
        }
        if (!("isccPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["isccPath"] = "";
        }
        if (!("defaultDirName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["defaultDirName"] = "";
        }
        if (!("privilegesRequired" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["privilegesRequired"] = "";
        }
        if (!("setupIcon" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["setupIcon"] = "";
        }
        if (!("outputBaseName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["outputBaseName"] = "";
        }
        if (!("createDesktopShortcut" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["createDesktopShortcut"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowsConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WindowsConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WindowsConfig(/** @type {Partial<WindowsConfig>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = ToolCheck.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = Artifact.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = ProjectInfo.createFrom;
const $$createType6 = BuildSettings.createFrom;
const $$createType7 = ProgramEntry.createFrom;
const $$createType8 = PackagingAsset.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = WindowsConfig.createFrom;
const $$createType11 = MacOSConfig.createFrom;
const $$createType12 = ArtifactConfig.createFrom;
const $$createType13 = WailsProjectManager.createFrom;
const $$createType14 = WailsAppInfo.createFrom;
const $$createType15 = WailsFileAssociation.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = WailsProjectConfig.createFrom;
const $$createType18 = WailsTaskVars.createFrom;
