// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Artifact {
    /**
     * Creates a new Artifact instance.
     * @param {Partial<Artifact>} [$$source = {}] - The source object to create the Artifact.
     */
    constructor($$source = {}) {
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {UnixTime}
             */
            this["createdAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Artifact instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Artifact}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Artifact(/** @type {Partial<Artifact>} */($$parsedSource));
    }
}

export class EnvironmentReport {
    /**
     * Creates a new EnvironmentReport instance.
     * @param {Partial<EnvironmentReport>} [$$source = {}] - The source object to create the EnvironmentReport.
     */
    constructor($$source = {}) {
        if (!("os" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["os"] = "";
        }
        if (!("arch" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["arch"] = "";
        }
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("checks" in $$source)) {
            /**
             * @member
             * @type {ToolCheck[]}
             */
            this["checks"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnvironmentReport instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EnvironmentReport}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("checks" in $$parsedSource) {
            $$parsedSource["checks"] = $$createField3_0($$parsedSource["checks"]);
        }
        return new EnvironmentReport(/** @type {Partial<EnvironmentReport>} */($$parsedSource));
    }
}

export class LogLineEvent {
    /**
     * Creates a new LogLineEvent instance.
     * @param {Partial<LogLineEvent>} [$$source = {}] - The source object to create the LogLineEvent.
     */
    constructor($$source = {}) {
        if (!("line" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["line"] = "";
        }
        if (!("transactionId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["transactionId"] = "";
        }
        if (!("transactionType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["transactionType"] = "";
        }
        if (!("transactionTitle" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["transactionTitle"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogLineEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LogLineEvent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogLineEvent(/** @type {Partial<LogLineEvent>} */($$parsedSource));
    }
}

export class ManagerSettings {
    /**
     * Creates a new ManagerSettings instance.
     * @param {Partial<ManagerSettings>} [$$source = {}] - The source object to create the ManagerSettings.
     */
    constructor($$source = {}) {
        if (!("isDark" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isDark"] = false;
        }
        if (!("language" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["language"] = "";
        }
        if (!("recordLogs" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["recordLogs"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ManagerSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ManagerSettings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ManagerSettings(/** @type {Partial<ManagerSettings>} */($$parsedSource));
    }
}

export class PackageRequest {
    /**
     * Creates a new PackageRequest instance.
     * @param {Partial<PackageRequest>} [$$source = {}] - The source object to create the PackageRequest.
     */
    constructor($$source = {}) {
        if (!("projectDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["projectDir"] = "";
        }
        if (!("platform" in $$source)) {
            /**
             * @member
             * @type {Platform}
             */
            this["platform"] = Platform.$zero;
        }
        if (!("dryRun" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["dryRun"] = false;
        }
        if (!("runBuild" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["runBuild"] = false;
        }
        if (!("transactionId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["transactionId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PackageRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PackageRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PackageRequest(/** @type {Partial<PackageRequest>} */($$parsedSource));
    }
}

export class PackageResult {
    /**
     * Creates a new PackageResult instance.
     * @param {Partial<PackageResult>} [$$source = {}] - The source object to create the PackageResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["runId"] = undefined;
        }
        if (!("artifacts" in $$source)) {
            /**
             * @member
             * @type {Artifact[]}
             */
            this["artifacts"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["warnings"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["buildOutputDir"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["packageOutputDir"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PackageResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PackageResult}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType3;
        const $$createField4_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("artifacts" in $$parsedSource) {
            $$parsedSource["artifacts"] = $$createField3_0($$parsedSource["artifacts"]);
        }
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField4_0($$parsedSource["warnings"]);
        }
        return new PackageResult(/** @type {Partial<PackageResult>} */($$parsedSource));
    }
}

/**
 * @typedef {any} PackagingConfig
 */

export class PackagingRuntimeInfo {
    /**
     * Creates a new PackagingRuntimeInfo instance.
     * @param {Partial<PackagingRuntimeInfo>} [$$source = {}] - The source object to create the PackagingRuntimeInfo.
     */
    constructor($$source = {}) {
        if (!("defaultExecutablePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["defaultExecutablePath"] = "";
        }
        if (!("effectiveExecutablePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["effectiveExecutablePath"] = "";
        }
        if (!("usingDefaultExecutable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["usingDefaultExecutable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PackagingRuntimeInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PackagingRuntimeInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PackagingRuntimeInfo(/** @type {Partial<PackagingRuntimeInfo>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const Platform = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    PlatformAuto: "auto",
    PlatformWindows: "windows",
    PlatformMacOS: "darwin",
    PlatformAll: "all",
};

export class ProjectRecord {
    /**
     * Creates a new ProjectRecord instance.
     * @param {Partial<ProjectRecord>} [$$source = {}] - The source object to create the ProjectRecord.
     */
    constructor($$source = {}) {
        if (!("projectDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["projectDir"] = "";
        }
        if (!("project" in $$source)) {
            /**
             * @member
             * @type {WailsProjectManager}
             */
            this["project"] = (new WailsProjectManager());
        }
        if (!("importedAt" in $$source)) {
            /**
             * @member
             * @type {UnixTime}
             */
            this["importedAt"] = null;
        }
        if (!("lastOpenedAt" in $$source)) {
            /**
             * @member
             * @type {UnixTime}
             */
            this["lastOpenedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectRecord instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProjectRecord}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("project" in $$parsedSource) {
            $$parsedSource["project"] = $$createField1_0($$parsedSource["project"]);
        }
        return new ProjectRecord(/** @type {Partial<ProjectRecord>} */($$parsedSource));
    }
}

export class ScanResult {
    /**
     * Creates a new ScanResult instance.
     * @param {Partial<ScanResult>} [$$source = {}] - The source object to create the ScanResult.
     */
    constructor($$source = {}) {
        if (!("projectDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["projectDir"] = "";
        }
        if (!("score" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["score"] = 0;
        }
        if (!("isWailsProject" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isWailsProject"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScanResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScanResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScanResult(/** @type {Partial<ScanResult>} */($$parsedSource));
    }
}

export class ToolCheck {
    /**
     * Creates a new ToolCheck instance.
     * @param {Partial<ToolCheck>} [$$source = {}] - The source object to create the ToolCheck.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("command" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["command"] = "";
        }
        if (!("found" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["found"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["version"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["path"] = undefined;
        }
        if (!("required" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["required"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Platform | undefined}
             */
            this["platform"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolCheck instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ToolCheck}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToolCheck(/** @type {Partial<ToolCheck>} */($$parsedSource));
    }
}

/**
 * UnixTime stores timestamps as Unix seconds in JSON.
 * @typedef {any} UnixTime
 */

export class WailsAppInfo {
    /**
     * Creates a new WailsAppInfo instance.
     * @param {Partial<WailsAppInfo>} [$$source = {}] - The source object to create the WailsAppInfo.
     */
    constructor($$source = {}) {
        if (!("companyName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["companyName"] = "";
        }
        if (!("productName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["productName"] = "";
        }
        if (!("productIdentifier" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["productIdentifier"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("copyright" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["copyright"] = "";
        }
        if (!("comments" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["comments"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WailsAppInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WailsAppInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WailsAppInfo(/** @type {Partial<WailsAppInfo>} */($$parsedSource));
    }
}

export class WailsFileAssociation {
    /**
     * Creates a new WailsFileAssociation instance.
     * @param {Partial<WailsFileAssociation>} [$$source = {}] - The source object to create the WailsFileAssociation.
     */
    constructor($$source = {}) {
        if (!("ext" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ext"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("iconName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["iconName"] = "";
        }
        if (!("role" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["role"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["mimeType"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WailsFileAssociation instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WailsFileAssociation}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WailsFileAssociation(/** @type {Partial<WailsFileAssociation>} */($$parsedSource));
    }
}

export class WailsProjectConfig {
    /**
     * Creates a new WailsProjectConfig instance.
     * @param {Partial<WailsProjectConfig>} [$$source = {}] - The source object to create the WailsProjectConfig.
     */
    constructor($$source = {}) {
        if (!("info" in $$source)) {
            /**
             * @member
             * @type {WailsAppInfo}
             */
            this["info"] = (new WailsAppInfo());
        }
        if (!("icon" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {WailsFileAssociation[] | undefined}
             */
            this["fileAssociations"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WailsProjectConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WailsProjectConfig}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType6;
        const $$createField2_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("info" in $$parsedSource) {
            $$parsedSource["info"] = $$createField0_0($$parsedSource["info"]);
        }
        if ("fileAssociations" in $$parsedSource) {
            $$parsedSource["fileAssociations"] = $$createField2_0($$parsedSource["fileAssociations"]);
        }
        return new WailsProjectConfig(/** @type {Partial<WailsProjectConfig>} */($$parsedSource));
    }
}

export class WailsProjectManager {
    /**
     * Creates a new WailsProjectManager instance.
     * @param {Partial<WailsProjectManager>} [$$source = {}] - The source object to create the WailsProjectManager.
     */
    constructor($$source = {}) {
        if (!("projectDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["projectDir"] = "";
        }
        if (!("currentPlatform" in $$source)) {
            /**
             * @member
             * @type {Platform}
             */
            this["currentPlatform"] = Platform.$zero;
        }
        if (!("wailsConfig" in $$source)) {
            /**
             * @member
             * @type {WailsProjectConfig}
             */
            this["wailsConfig"] = (new WailsProjectConfig());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WailsProjectManager instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WailsProjectManager}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("wailsConfig" in $$parsedSource) {
            $$parsedSource["wailsConfig"] = $$createField2_0($$parsedSource["wailsConfig"]);
        }
        return new WailsProjectManager(/** @type {Partial<WailsProjectManager>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = ToolCheck.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = Artifact.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = WailsProjectManager.createFrom;
const $$createType6 = WailsAppInfo.createFrom;
const $$createType7 = WailsFileAssociation.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = WailsProjectConfig.createFrom;
