//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as contracts$0 from "../../../../../wails3-manager/core/contracts/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "manager:log-line": $$createType0,
    }));
}

// Private type creation functions
const $$createType0 = contracts$0.LogLineEvent.createFrom;

configure();
