// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as contracts$0 from "../contracts/models.js";

/**
 * @param {string} projectDir
 * @returns {$CancellablePromise<void>}
 */
export function ImportProject(projectDir) {
    return $Call.ByID(3467381582, projectDir);
}

/**
 * @param {string} projectDir
 * @param {string} pngBase64
 * @returns {$CancellablePromise<contracts$0.ProjectRecord>}
 */
export function ReplaceProjectIcon(projectDir, pngBase64) {
    return $Call.ByID(1035802352, projectDir, pngBase64).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {contracts$0.ProjectRecord} record
 * @returns {$CancellablePromise<contracts$0.ProjectRecord>}
 */
export function SaveProject(record) {
    return $Call.ByID(3657298558, record).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} projectDir
 * @returns {$CancellablePromise<contracts$0.ScanResult>}
 */
export function ScanProject(projectDir) {
    return $Call.ByID(3127479482, projectDir).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = contracts$0.ProjectRecord.createFrom;
const $$createType1 = contracts$0.ScanResult.createFrom;
