// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as contracts$0 from "../contracts/models.js";

/**
 * @returns {$CancellablePromise<void>}
 */
export function ClearLogs() {
    return $Call.ByID(1581465028);
}

/**
 * @param {string} projectDir
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function GetABSPath(projectDir, path) {
    return $Call.ByID(4174862789, projectDir, path);
}

/**
 * @returns {$CancellablePromise<contracts$0.ManagerSettings>}
 */
export function GetSettings() {
    return $Call.ByID(907575087).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<contracts$0.ProjectRecord[]>}
 */
export function ListProjects() {
    return $Call.ByID(1990199896).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} projectDir
 * @returns {$CancellablePromise<contracts$0.ProjectRecord>}
 */
export function OpenProject(projectDir) {
    return $Call.ByID(4133492287, projectDir).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} projectDir
 * @param {boolean} restoreOriginal
 * @returns {$CancellablePromise<void>}
 */
export function RemoveProject(projectDir, restoreOriginal) {
    return $Call.ByID(674460619, projectDir, restoreOriginal);
}

/**
 * @param {contracts$0.ManagerSettings} settings
 * @returns {$CancellablePromise<contracts$0.ManagerSettings>}
 */
export function SaveSettings(settings) {
    return $Call.ByID(3687326086, settings).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = contracts$0.ManagerSettings.createFrom;
const $$createType1 = contracts$0.ProjectRecord.createFrom;
const $$createType2 = $Create.Array($$createType1);
