package creator

import (
	"context"
	"os"
	"path/filepath"
	"reflect"
	"testing"

	"wails3-manager/core/contracts"
)

type fakeRunner struct {
	workDir string
	command []string
	run     func(workDir string, command []string) error
}

func (r *fakeRunner) Run(_ context.Context, workDir string, command []string) error {
	r.workDir = workDir
	r.command = append([]string{}, command...)
	if r.run != nil {
		return r.run(workDir, command)
	}
	return nil
}

func TestCreateWailsProjectBuildsInitCommandAndReturnsAbsolutePath(t *testing.T) {
	targetDir := filepath.Join(t.TempDir(), "demo")
	runner := &fakeRunner{
		run: func(_ string, _ []string) error {
			return os.MkdirAll(targetDir, 0755)
		},
	}
	service := &CreatorService{Runner: runner}

	got, err := service.CreateWailsProject(contracts.CreateWailsProjectRequest{
		Name:                      " demo ",
		Dir:                       targetDir,
		GoModule:                  "github.com/example/demo",
		Git:                       "github.com/example/demo",
		ProductName:               "Demo Product",
		ProductDescription:        "Demo Description",
		ProductVersion:            "1.2.3",
		ProductCompany:            "Example Inc",
		ProductCopyright:          "Copyright 2026 Example Inc",
		ProductComments:           "Generated by test",
		ProductIdentifier:         "com.example.demo",
		Quiet:                     true,
		SkipRemoteTemplateWarning: true,
		SkipGoModTidy:             true,
	})
	if err != nil {
		t.Fatal(err)
	}

	absTarget, err := filepath.Abs(targetDir)
	if err != nil {
		t.Fatal(err)
	}
	if got != filepath.Clean(absTarget) {
		t.Fatalf("CreateWailsProject() = %q, want %q", got, filepath.Clean(absTarget))
	}

	want := []string{
		"wails3", "init",
		"-n", "demo",
		"-d", filepath.Clean(absTarget),
		"-t", "vanilla",
		"-p", "main",
		"-nocolour",
		"-mod", "github.com/example/demo",
		"-git", "github.com/example/demo",
		"-productname", "Demo Product",
		"-productdescription", "Demo Description",
		"-productversion", "1.2.3",
		"-productcompany", "Example Inc",
		"-productcopyright", "Copyright 2026 Example Inc",
		"-productcomments", "Generated by test",
		"-productidentifier", "com.example.demo",
		"-q",
		"-s",
		"-skipgomodtidy",
	}
	if !reflect.DeepEqual(runner.command, want) {
		t.Fatalf("command = %#v, want %#v", runner.command, want)
	}
	if runner.workDir != filepath.Dir(filepath.Clean(absTarget)) {
		t.Fatalf("workDir = %q, want %q", runner.workDir, filepath.Dir(filepath.Clean(absTarget)))
	}
}

func TestCreateWailsProjectUsesTemplateAndPackageDefaults(t *testing.T) {
	targetDir := filepath.Join(t.TempDir(), "demo")
	runner := &fakeRunner{
		run: func(_ string, _ []string) error {
			return os.MkdirAll(targetDir, 0755)
		},
	}
	service := &CreatorService{Runner: runner}

	if _, err := service.CreateWailsProject(contracts.CreateWailsProjectRequest{Name: "demo", Dir: targetDir}); err != nil {
		t.Fatal(err)
	}

	want := []string{
		"wails3", "init",
		"-n", "demo",
		"-d", filepath.Clean(targetDir),
		"-t", "vanilla",
		"-p", "main",
		"-nocolour",
	}
	if !reflect.DeepEqual(runner.command, want) {
		t.Fatalf("command = %#v, want %#v", runner.command, want)
	}
}

func TestCreateWailsProjectRejectsNonEmptyTargetDirectory(t *testing.T) {
	targetDir := filepath.Join(t.TempDir(), "demo")
	if err := os.MkdirAll(targetDir, 0755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(targetDir, "README.md"), []byte("demo"), 0644); err != nil {
		t.Fatal(err)
	}

	runner := &fakeRunner{}
	service := &CreatorService{Runner: runner}

	if _, err := service.CreateWailsProject(contracts.CreateWailsProjectRequest{Name: "demo", Dir: targetDir}); err == nil {
		t.Fatal("expected non-empty target directory to be rejected")
	}
	if len(runner.command) != 0 {
		t.Fatalf("runner should not be called, command=%#v", runner.command)
	}
}
