// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as contracts$0 from "../contracts/models.js";

/**
 * @param {string} projectDir
 * @returns {$CancellablePromise<contracts$0.Artifact[]>}
 */
export function Artifacts(projectDir) {
    return $Call.ByID(4259891839, projectDir).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} projectDir
 * @returns {$CancellablePromise<contracts$0.PackagingConfig>}
 */
export function InitPackaging(projectDir) {
    return $Call.ByID(3023897689, projectDir).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} projectDir
 * @returns {$CancellablePromise<contracts$0.PackagingConfig>}
 */
export function LoadPackagingConfig(projectDir) {
    return $Call.ByID(1696901017, projectDir).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {contracts$0.PackageRequest} req
 * @returns {$CancellablePromise<contracts$0.PackageResult>}
 */
export function Package(req) {
    return $Call.ByID(1680800692, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} projectDir
 * @param {contracts$0.PackagingConfig} cfg
 * @returns {$CancellablePromise<contracts$0.PackagingConfig>}
 */
export function SavePackagingConfig(projectDir, cfg) {
    return $Call.ByID(3548482574, projectDir, cfg).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

// Private type creation functions
const $$createType0 = contracts$0.Artifact.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = contracts$0.PackagingConfig.createFrom;
const $$createType3 = contracts$0.PackageResult.createFrom;
